### ISSUE TITLE
파이썬 교육: EIR 산출하기

### ISSUE THREAD

**Issue by oolongsawel** [IFRS17/pythonEdu#2]
다음주제
파이썬을 EIR산출하기 (목표값 못찾을 경우 가장 가까운 값으로 출력해주기)

요청사항 ( @g1leftfinger @g1rightfinger )
1. 실제 업무 시나리오 설정
2. 구현 로직 자료 요청
3. 업무 시나리오와 구현 로직을 바탕으로 파이썬 개발 해보기

**Comment by tooget** [comment]
@g1rightfinger EIR 계산하는 업무 프로세스, 방정식(DCF?) + 답 안나오는 현금흐름 설명을 어떻게 하면 들을 수 있을까요?
따로 시간을 한 번 잡는 게 좋을까요?

**Comment by tooget** [comment]
2023-01-20 EIR 계산기 핸즈온 완료
@oolongsawel @tooget @g1leftfinger @g1rightfinger
